### ISSUE TITLE
Left sidebar is not work

### ISSUE THREAD

**Issue by errogaht** [ryan-roemer/sphinx-bootstrap-theme#100]
Hello, your work is great, but im cant find - how to make left side bar
this is what i have:
http://shot.qip.ru/00kmMg-5tOAcrHwv/

**Comment by NLPDev** [comment]
html_sidebars = {
   '**': ['globaltoc.html', 'sourcelink.html', 'searchbox.html'],  
}

Please add this in conf.py
Thanks.

**Comment by ryan-roemer** [comment]
Looks like we've got a solution here. Thanks!
