### ISSUE TITLE
Slow loading speed

### ISSUE THREAD

**Issue by UnderClock** [ryan-roemer/sphinx-bootstrap-theme#108]
I am not sure whether this is a sphinx-bootstrap-theme issue or not.
I am using sphinx-bootstrap-theme for my online help.

It slows down page loading on the pages if I specify 'bootswatch_theme': "flatly" or other theme options. My help is fine if I don't specify that option.

My console said "Fail to load resource :  net::ERR_FILE_NOT_FOUND ... file://fonts.googleapis.com/css?family=Lato:400,700,900,400italic

I am using latest version of Google Chrome(36.0.1985.143), and the help is built with Sphinx (sphinx-build) 1.2 

Any ideas or help?

Thank you.

**Comment by ppyv** [comment]
It's already fixed on bootswatch recent release. @ryan-roemer, do you have any plan to take them in?

**Comment by ryan-roemer** [comment]
@ppyv -- PRs welcome for bootswatch updates.

@UnderClock -- Make sure to run a static http server when using the theme (or well anything on the web) if you're running `file://` issues. `//` is "protocol independent" resourcing, and although falling out of favor in lieu of always using `https://`, is still widely out there for many web resources we might use.

Fortunately, python includes simpleserver by default. See https://github.com/ryan-roemer/sphinx-bootstrap-theme#contributing for links to how we run demo servers for this theme in development for pointers.

**Comment by ppyv** [comment]
@ryan-roemer Thanks your reply, and I've sent a PR.
