### ISSUE TITLE
How do I add this theme for RTD

### ISSUE THREAD

**Issue by pdion891** [ryan-roemer/sphinx-bootstrap-theme#125]
How can I add this theme for existing project hosted on readthedocs.org ? 
If I add it with ``html_theme_path = [ "./_themes/" ]`` I  end up with missing css for the RTD badge.

If I add the theme as the README.rst (https://github.com/ryan-roemer/sphinx-bootstrap-theme#installation) the project fail to build on RTD.

exemple: http://acs-install-doctests.readthedocs.org/en/bootstrap/choosing_deployment_architecture.html

**Comment by ryan-roemer** [comment]
I'm not actually sure, but maybe try this:

```py
html_theme_path = ["./_themes/"] + sphinx_bootstrap_theme.get_html_theme_path()
```

If that's not sufficient, them maybe go further with some of the tweaks in http://sphinxjpthemesbasicstrap.readthedocs.org/en/latest/options.html that I found googling around from another project. E.g., some of the tweaks look like...

```py
import sphinx_bootstrap_theme

# ... Rest of config

if "html_theme_path" in globals():
    html_theme_path += sphinx_bootstrap_theme.get_html_theme_path()
else:
    html_theme_path = ["./_themes/"] + sphinx_bootstrap_theme.get_html_theme_path()
```

And then there's a lot of other analogous stuff.

Good luck!

**Comment by pdion891** [comment]
Hi @ryan-roemer , thanks for the help! 

I did try all of these and it's still not working :-S   I will continu to look how to make this work on RTD, which shouldn't be that complicated as the demo from this project is hosted on it ...

When using this: it seams to fail at the import line:  maybe it as to do with a standard location of the theme into the rtd project? where would this be...
```
import sphinx_bootstrap_theme

# ... Rest of config

# Hack around with the following in local / RTD...
if "html_theme_path" in globals():
    html_theme_path += sphinx_bootstrap_theme.get_html_theme_path()
else:
    html_theme_path = ["./_themes/"] + sphinx_bootstrap_theme.get_html_theme_path()
```

**Comment by ryan-roemer** [comment]
@pdion891 -- Unfortunately, I'm unfamiliar with how package dependencies / `import`'s work in RTD.

From the RTD build doc (http://docs.readthedocs.org/en/latest/builds.html) it looks like adding SBT to your requirements doc _should_ make it available for the `import`... (?)

**Comment by pdion891** [comment]
Looks like I've got it fixed! 

starting from downloaded .zip files,   copied ``sphinx_bootstrap_theme``  and create a symlink ``bootstrap`` to ``sphinx_bootstrap_theme/bootstrap``
and conf.py:
```
sys.path.insert(0, os.path.abspath('../'))
import sphinx_bootstrap_theme
```

and it's now working on RTD. 

@ryan-roemer , Thanks for your help and this project!

**Comment by Suyashtnt** [comment]
this is a very old thread but how exactly do I create a symlink? new to python, RTD, Sphinx and this theme
