### ISSUE TITLE
Upgrade bootstrap to version 3.3.4

### ISSUE THREAD

**Issue by hermanbergwerf** [ryan-roemer/sphinx-bootstrap-theme#127]
I'd like to use the latest Bootswatch Paper theme (since it has added a cool ripple effect)
Could you upgrade bootstrap to the latest version?

**Comment by ryan-roemer** [comment]
Yep, we were definitely overdue for an update!

Released in https://pypi.python.org/pypi/sphinx-bootstrap-theme/0.4.6
