### ISSUE TITLE
CSS problems with 0.4.6 in navbar_title

### ISSUE THREAD

**Issue by ElDeveloper** [ryan-roemer/sphinx-bootstrap-theme#133]
When using version 0.4.6, it seems like there's a problem with the CSS that makes the `navbar_title` float in the middle of the navbar:

![screen shot 2015-06-16 at 10 47 30 am](https://cloud.githubusercontent.com/assets/375307/8190072/4d239a9e-1415-11e5-96c1-6827cdf00fcc.png)

This problem is not present in 0.4.5:

![screen shot 2015-06-16 at 10 50 02 am](https://cloud.githubusercontent.com/assets/375307/8190100/7702236c-1415-11e5-8cd9-1bdc6ca7dc71.png)

**Comment by ryan-roemer** [comment]
@ElDeveloper -- Looking at https://github.com/ryan-roemer/sphinx-bootstrap-theme/compare/v0.4.5...v0.4.6 it looks like we didn't change any CSS in the theme itself. However, we _did_ upgrade the underlying bootstrap / bootswatch libraries. Can you check if there was something in that diff for Bootstrap that changed and possibly suggest a change for the theme?

**Comment by ElDeveloper** [comment]
From looking at a few of those files, I cannot spot anything that might
be immediately obvious. I've also looked at
https://github.com/twbs/bootstrap/releases and couldn't find anything.
Alternatively, I've also changed the size of the image to be 24x24 (as
suggested in the docs) but that didn't help either.

**Comment by ryan-roemer** [comment]
@ElDeveloper -- What would be super-useful is if you could open a pull request with changes to the Demo site to expose the issue so I can debug it? (I'll throw away the PR, so you can add gibberish text wherever). Thanks!

**Comment by ElDeveloper** [comment]
Just submitted https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/134
thanks a lot for the help!

**Comment by ryan-roemer** [comment]
@ElDeveloper -- I do see the issue, and it's pretty much this: https://github.com/twbs/bootstrap/issues/15222

Specifically, BS changed to have this:

```css
.navbar-brand > img {
  display: block;
}
```

I'll investigate further to see if there's something "sensible" to do here. (Strictly speaking, the theme doesn't try to "fix" things in BS, just pass them through...)

**Comment by ryan-roemer** [comment]
@ElDeveloper -- Can you try adding a custom CSS file per the instructions in https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/master/README.rst#adding-custom-css and see if the following fixes the problem for you?

```css
.navbar-brand > img {
  display: inline-block;
}
```

**Comment by ElDeveloper** [comment]
@ryan-roemer, thanks so much for the help! This works great!!
