### ISSUE TITLE
Auto-hiding navbar?

### ISSUE THREAD

**Issue by mgeier** [ryan-roemer/sphinx-bootstrap-theme#138]
I know the `navbar_fixed_top` option, which is very handy, but is there also an option for auto-hiding the navbar?

If not, would it be possible to include https://github.com/istvan-ujjmeszaros/bootstrap-autohidingnavbar?

**Comment by ryan-roemer** [comment]
@mgeier -- Thanks for the suggestion, but we're only including bootstrap + bootswatch in the core library.

Fortunately, you can [override the layout template](https://github.com/ryan-roemer/sphinx-bootstrap-theme#extending-layouthtml) in your own projects quite easily with perhaps something like:

```
{%- extends "layout.html" %}
{% set script_files = script_files + ["MY_EXTRA_FILE_OR_URL.js"] %}
```

**Comment by mgeier** [comment]
OK, thanks for the hint, I'll try that.

Great theme, BTW!
