### ISSUE TITLE
CSS for mobile size layout seems to break logo on readthedocs

### ISSUE THREAD

**Issue by zxiiro** [ryan-roemer/sphinx-bootstrap-theme#142]
We're using the sphinx bootstrap theme for our readthedocs page and notice that the mobile page seems to break if you provide a small logo.

For example http://docs.opendaylight.org/ and resize the browser to mobile size.

Looks like ReadTheDocs injects some css into the site that's causing the issue. Injecting the following link into your header is enough to reproduce the issue on a local build.

```
    <link rel="stylesheet" href="https://media.readthedocs.org/css/badge_only.css" type="text/css" />
```

**Comment by zxiiro** [comment]
Just realised readthedocs builds with an older sphinx version by default that causes the logo issue. Upgrading to a newer sphinx version helps.

**Comment by zxiiro** [comment]
Did some more troubleshooting here and discovered that readthedocs inserts some css below which causes the mobile site to draw the logo way too big.

`<link rel="stylesheet" href="https://media.readthedocs.org/css/badge_only.css" type="text/css" />`

**Comment by ryan-roemer** [comment]
Holy moly, you aren't kidding!!!

<img width="587" alt="screen shot 2016-07-08 at 1 08 37 pm" src="https://cloud.githubusercontent.com/assets/445557/16700137/2e58bf52-450d-11e6-95ec-d0d1f38e813e.png">

@zxiiro -- Do you have any suggestions for a fix? Or which styling is messing with the theme?

The unfortunate thing here is that the RTD CSS comes _after_ the theme's...

**Comment by zxiiro** [comment]
Unfortunately not. I don't spend too much time doing web dev stuff so not too familiar with all this.

**Comment by zxiiro** [comment]
Just spotted a few more possible candidates that could be causing the issue:


```
    <script type="text/javascript" src="https://media.readthedocs.org/javascript/jquery/jquery-2.0.3.min.js"></script>
    <script type="text/javascript" src="https://media.readthedocs.org/javascript/jquery/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="https://media.readthedocs.org/javascript/underscore.js"></script>
    <script type="text/javascript" src="https://media.readthedocs.org/javascript/doctools.js"></script>
    <script type="text/javascript" src="https://media.readthedocs.org/javascript/readthedocs-doc-embed.js"></script>
```

I'll update the description so that all the details are in one place.

**Comment by ryan-roemer** [comment]
@zxiiro -- No worries. I'm not a styles person myself, but I know some folks that are and they're helping me 😉

**Comment by zxiiro** [comment]
Ok I tracked it down to the specific lines of code from readthedocs' css hopefull this helps you move forward.

```
@media screen and (max-width: 768px) {
    .rst-versions {
        width: 85%;
        display: none
    }
    .rst-versions.shift {
        display: block
    }
    img {
        width: 100%;
        height: auto
    }
}
```

The "width: 100%" field inside the img tag is what's causing the logo to get stretched.
