### ISSUE TITLE
Release 0.4.12 tag is missing

### ISSUE THREAD

**Issue by bendiken** [ryan-roemer/sphinx-bootstrap-theme#145]
It would seem that the v0.4.12 tag has not been created and/or pushed yet, despite this version having already been released on PyPI:

* https://github.com/ryan-roemer/sphinx-bootstrap-theme/releases/tag/v0.4.12
* https://pypi.python.org/pypi/sphinx-bootstrap-theme/0.4.12

**Comment by ryan-roemer** [comment]
haha, forgot ye olde `git push --tags`....

https://github.com/ryan-roemer/sphinx-bootstrap-theme/tree/v0.4.12 is up now.

**Comment by bendiken** [comment]
Thanks!
