### ISSUE TITLE
Multiple footnote references render incorrectly

### ISSUE THREAD

**Issue by drewhutchison** [ryan-roemer/sphinx-bootstrap-theme#151]
This probably isn't a common use-case, but I sometimes reuse the same footnote reference to save space and boilerplate. This renders incorrectly under default settings.

A minimal example reproduces the issue:

```
[1]_ [1]_

.. [1] sample note
```

which renders as:

```
<p><a class="footnote-reference" href="#id3" id="id1">[1]</a> <a class="footnote-reference" href="#id3" id="id2">[1]</a></p>
<table class="docutils footnote" frame="void" id="id3" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label">[1]</td><td><em>(<a class="fn-backref" href="#id1">1</a>, <a class="fn-backref" href="#id2">2</a>)</em> sample note</td></tr>
</tbody>
</table>
```

which is fine, except the `.label` styles as `color: #ffffff` from the 3.3.6 bootstrap.min.css.

This may be resolved by

```
--- a/sphinx_bootstrap_theme/bootstrap/static/bootstrap-sphinx.css_t
+++ b/sphinx_bootstrap_theme/bootstrap/static/bootstrap-sphinx.css_t
@@ -94,6 +94,7 @@ a.footnote-reference {
 }
 
 table.footnote td.label {
+  color: #333;
   font-size: 100%;
   display: block;
   line-height: normal;
```

but I'm not sure what effect that might have on other styles.

**Comment by ryan-roemer** [comment]
@drewhutchison -- Can you open a PR with your actual proposed changes with changes to https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/master/demo/source/examples.rst to show more of what you mean with repeated footnotes?

Separately include instructions for local modifications if necessary (like a different bootswatch theme, etc.)

... I'll then review and take it from there. Thanks!

**Comment by drewhutchison** [comment]
Thanks Ryan, somehow totally missed the examples file or I'd have done this to being with! See #152.
