### ISSUE TITLE
TypeError when css_files is None with Sphinx 1.6

### ISSUE THREAD

**Issue by jaraco** [ryan-roemer/sphinx-bootstrap-theme#160]
Using Sphinx 1.6.1, running quickstart, then configuring sphinx_bootstrap_theme according to the README, the docs fail to build with this error:

```
Exception occurred:
  File "/Users/jaraco/.envs/sphinx/lib/python3.6/site-packages/sphinx_bootstrap_theme/bootstrap/layout.html", line 40, in top-level template code
    {% set css_files = css_files + theme_css_files + bootswatch_css_custom %}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

This issue emerged as part of the Sphinx 1.6 release. Pinning to Sphinx 1.5.6 works around the issue.

**Comment by jaraco** [comment]
I've pushed [a minimal project](/jaraco/bootstrap-theme-issue-160) to this repo for easy testing.

**Comment by ryan-roemer** [comment]
Hey @jaraco !!!!

How's it going?

Anyhoo, to the issue at hand -- I'm working on it at https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/159#issuecomment-302159230  The main issue's fixed, but I still need to support "adding extra CSS" in some documented, idiomatic way...

Head on over there!

**Comment by jaraco** [comment]
> How's it going?

Quite well, and was pleased to bump into you here, even to create work for you. Glad you were essentially already on it. Hope you're well.
