### ISSUE TITLE
Error when sidebar is larger than content

### ISSUE THREAD

**Issue by awholegunch** [ryan-roemer/sphinx-bootstrap-theme#161]
The fix for issue https://github.com/ryan-roemer/sphinx-bootstrap-theme/issues/147 doesn't seem to work correctly, as there is no jQuery minHeight function. This is happening on pages where the content is smaller than the left sidebar.

I am seeing:
```
$content.minHeight is not a function. (In '$content.minHeight($sideBar.outerHeight(true))', '$content.minHeight' is undefined)
```
I fixed it by making this change in `bootstrap-sphinx.js` (https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/master/sphinx_bootstrap_theme/bootstrap/static/bootstrap-sphinx.js_t#L100):
```
//         $content.minHeight($sideBar.outerHeight(true));
        $content[0].style.minHeight = $sideBar.outerHeight(true) + 'px';
```

**Comment by ryan-roemer** [comment]
@awholegunch -- Can you try out https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/157 and comment there to see if that fixes things for you?

(I'm guessing sphinx upgraded jQuery in a more modern version -- which version of `sphinx` are you on?)
