### ISSUE TITLE
Different results with Sphinx 1.6.2

### ISSUE THREAD

**Issue by pcav** [ryan-roemer/sphinx-bootstrap-theme#162]
The website: http://www.faunalia.eu, built from https://github.com/pcav/faunalia-website renders differently with Sphinx 1.6.2 and 1.5.5. In 1.6.2, background is yellow, whereas in 1.5.5 is (as desired) white.
Compiled HTML available on request.
Thanks.

**Comment by ryan-roemer** [comment]
Which background are you talking about? I see a white background here:

<img width="1371" alt="screen shot 2017-05-30 at 9 31 57 am" src="https://cloud.githubusercontent.com/assets/445557/26593999/e4614914-451a-11e7-8ab5-409dd2fd9cc7.png">

**Comment by pcav** [comment]
This is compiled with 1.5.5

**Comment by ryan-roemer** [comment]
If you can throw an example website with your new build up somewhere for me to look at, that would greatly aide my diagnosis. (If you need an easy, free and fast way to host a temporary website, http://surge.sh/ is great).

Then paste a link in this ticket and I'll take a look!

**Comment by ryan-roemer** [comment]
Beat me to it: http://www.faunalia.eu/~paolo/website_wrong/

Looking now :)

**Comment by pcav** [comment]
Thanks!

**Comment by ryan-roemer** [comment]
Looking in the style inspector you've added this line: https://github.com/pcav/faunalia-website/blob/571045b2144c664424886516905a179f06b21c49/_static/faunalia.css_t#L259

```css
	background:#fee653;
```

To your website's source in this commit: https://github.com/pcav/faunalia-website/commit/890972f371dae9e2c44622f981a45b55ac3cb15e four years ago. It was probably always buggy, but my offhand guess is that old Sphinx probably overrode the background in 1.5 and maybe didn't in 1.6

At any rate, this is entirely an issue with Sphinx vs. the faunalia website and not something with this theme.

Fortunately, I think if you remove that line from your `faunalia.css_t` CSS template the page will render as you would like it with a black background.

**Comment by pcav** [comment]
Thanks a lot, and sorry for the noise.

**Comment by ryan-roemer** [comment]
No worries -- a github issue + sample website for a quick reproduction makes this kind of diagnosis fairly straightforward. Thanks for the work on you end!
