### ISSUE TITLE
Unable to use certain Bootswatch themes

### ISSUE THREAD

**Issue by goodspark** [ryan-roemer/sphinx-bootstrap-theme#167]
Based on documentation, I assume I can use any free theme listed at https://bootswatch.com/

However, when I tried to use `materia` or `minty`, the theme was not applied to the generated docs.

But `superhero` and `flatly` work, FWIW.

I'm using the default bootstrap version (ie. 3). The only changes I'm making in my `conf.py` is the `bootswatch_theme` entry in the `html_theme_options` dict.

**Comment by svenevs** [comment]
@ryan-roemer It seems bootstrap 4 is no longer in beta.

@goodspark the themes that are currently available with this theme are [here](https://bootswatch.com/3/) -- those are the `v3.3.7` themes.  Basically, any folder name you see in [this folder](https://github.com/ryan-roemer/sphinx-bootstrap-theme/tree/master/sphinx_bootstrap_theme/bootstrap/static/bootswatch-3.3.7) is what's available for bootstrap 3.

**Comment by goodspark** [comment]
Ah, I see. Thank you!

**Comment by svenevs** [comment]
Referencing #146 :smile:
