### ISSUE TITLE
Add trove identifiers for supported Python versions

### ISSUE THREAD

**Issue by troeger** [ryan-roemer/sphinx-bootstrap-theme#174]
The [caniusepython3](https://github.com/brettcannon/caniusepython3) tool is used by some CI services (e.g. [pyup.io](pyup.io)) to check library dependencies for Python 3 support. This project fails in the check, since it has no [Trove identifiers](https://packaging.python.org/tutorials/distributing-packages/#classifiers) that declare the existing support for Python 3.

Test:
`pip install caniusepython3`
`caniusepython3 --projects sphinx-bootstrap-theme`

**Comment by svenevs** [comment]
@troeger we support python3, are you suggesting we change our classifier from

https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/e0ba650d8343a8ec4756cfa0c49ab37eaefc3953/setup.py#L55

to

```py
'Programming Language :: Python :: 2',
'Programming Language :: Python :: 3'
```

?  I had always interpreted `Programming Language :: Python` as "any python", but it doesn't appear that's standardized / possibly a relic from before Python3 was around?

**Comment by troeger** [comment]
Precisely. The semantics of trove identifiers are not formally fixed, there is only "common sense" floating around.

The modern way of declaring your supported versions would by the [python-requires](https://packaging.python.org/tutorials/distributing-packages/#python-requires) attribute, but this is only understood by the most recent PIP versions. Therefore, it would be great if you add the two lines above to your setup.py file.

**Comment by ryan-roemer** [comment]
Cool! @troeger -- Mind whipping us up a PR? Thanks!
