### ISSUE TITLE
html_sidebars broken in Spinx 1.7

### ISSUE THREAD

**Issue by iwelch82** [ryan-roemer/sphinx-bootstrap-theme#179]
My `conf.py` file has the following settings
```
html_sidebars = {'pages/**': ['localtoc.html', 'sourcelink.html',
                             'searchbox.html']}
```
When I run `make html` using Sphinx 1.6.7 the side bars only show up on pages under my `pages/` directory. When I update Sphinx to 1.7.0 the sidebar is displayed on every page. Furthermore, when I comment out sidebars all together they are still displayed on every page.  There is a comment in the [v1.7.0b1 release notes](http://www.sphinx-doc.org/en/stable/changes.html#release-1-7-0-released-feb-12-2018) that may allude to a fix

> HTML themes can set up default sidebars through theme.conf

**Comment by svenevs** [comment]
Thanks for letting us know @iwelch82!  I've asked the sphinx gods (https://groups.google.com/forum/#!topic/sphinx-dev/QTmNHPIeuf8) for help, I don't understand the hint here / how to employ it.

**Comment by has2k1** [comment]
I am not on the sphinx-dev mailing list.
> Deprecated since version 1.7: a single string value for html_sidebars will be removed in 2.0

`html_sidebars` was either a `string` or a `dict`, in the future it will be `dict` only.

I had just started using this selective sidebar feature, this looks like an upstream bug.

**Comment by svenevs** [comment]
I see, thank you.  That answers the question I asked there (what was being deprecated, and it is the type that `html_sidebars` can be in `conf.py`).  The layout code for this theme may also be a problem.

**Comment by tk0miya** [comment]
It might be a bug of Sphinx-1.6 or older. The default sidebar is `['localtoc.html', 'relations.html', 'sourcelink.html',  'searchbox.html']`.
So please give an empty list explicitly to `html_sidebars`:
```
html_sidebars = {
    'pages/**': ['localtoc.html', 'sourcelink.html', 'searchbox.html'],
    '**': [],
}
```

Thanks,

**Comment by svenevs** [comment]
@tk0miya thank you **very** much for following up on this!  This theme includes the information typically found in the sidebars in the main navbar at the top, I have fixed the `theme.conf` to automatically "add" `html_sidebars = {'**': []}` as shown [in the newer documentation](http://www.sphinx-doc.org/en/stable/theming.html#creating-themes).

Thanks again!

@iwelch82 for now as shown above you need to add `'**': []` in addition to what you already have.  I opened a PR that will remove the need for you to do this in the future :smile:
