### ISSUE TITLE
jquery 1.X is unsupported

### ISSUE THREAD

**Issue by opoplawski** [ryan-roemer/sphinx-bootstrap-theme#200]
jquery 1.X is no longer receiving updates, please consider updating to 3.X

**Comment by ryan-roemer** [comment]
What does bootstrap 3 and Sphinx each use these days? Are both jquery 3 compatible? Thanks!

**Comment by opoplawski** [comment]
Hmm, yes of course this is dependent on bootstrap.  3 still seems to bundle jquery 1.12.4.  bootstrap 5 (and maybe 4?) does not appear to need it at all.
