### ISSUE TITLE
PyPI package is out of date - 0.7.1 instead of 0.8.0

### ISSUE THREAD

**Issue by shlomif** [ryan-roemer/sphinx-bootstrap-theme#210]
See:

https://pypi.org/project/sphinx-bootstrap-theme/

Thanks!

**Comment by ryan-roemer** [comment]
We are now at https://pypi.org/project/sphinx-bootstrap-theme/0.8.0/ 🎉

**Comment by shlomif** [comment]
Thanks , @ryan-roemer !
