### ISSUE TITLE
Incompatible with newer setuptools (>=58.0.0) due to use of 2to3 in setup.py

### ISSUE THREAD

**Issue by willfurnass** [ryan-roemer/sphinx-bootstrap-theme#216]
There's been a breaking change in setuptools 58 (https://setuptools.readthedocs.io/en/latest/history.html): PR 2086

> removed support for 2to3 during builds. Projects should port to a unified codebase or pin to an older version of Setuptools using PEP 518 build-requires. 

Attempts to install this package alongside setuptools >= 58 result in:

```
    error in sphinx-bootstrap-theme setup command: use_2to3 is invalid.
```

is `2to3=True` still needed in `setup.py`?

**Comment by tanglef** [comment]
It seems the only file where `2to3` is really useful is in `fabfile.py` with urllib2 (that  and the fabric requirement that should be fabric3 in python3. Other than that I don't see why the use of `2to3=True`
