### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by pawelwoj** [ryan-roemer/sphinx-bootstrap-theme#220]
See:

http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html

**Comment by ryan-roemer** [comment]
Looks like a duplicate of https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/213

@pawelwoj can you test out that PR and see if it resolves the issue for you?

**Comment by pawelwoj** [comment]
I tried the search box on your demo page which uses sphinx-bootstrap-theme and it doesn't work for me (searching is suspended):

http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html

I have the same problem with my page that also uses  sphinx-bootstrap-theme. I didn't try fix #213, but I don't get the error message.

**Comment by ryan-roemer** [comment]
Yeah, the demo page isn't updated.

I didn't quite follow -- did #213 work for you when installed locally?

**Comment by pawelwoj** [comment]
I haven’t installed #213 yet.
