### ISSUE TITLE
Url ending with hash is rendered and used shortened

### ISSUE THREAD

**Issue by vlcinsky** [ryan-roemer/sphinx-bootstrap-theme#225]
Trying to show following url in my documentation:

- https://cef.uv.es/lodroadtran18/def/transporte/dtx_srti# - expected
- [https://cef.uv.es/lodroadtran18/def/transporte/](https://cef.uv.es/lodroadtran18/def/transporte/)dtx_srti# - rendered (shortened)

Whenever I use an url ending with hash, it gets shortened back to the nearest slash.

My source code for the docs is in rst.

I am using sphinx-bootstrap-theme==0.8.1

I would appreciate even some workaround (I have no chance to change the url).

**Comment by ryan-roemer** [comment]
As far as I can tell the page you're pointing to isn't actually using the theme even though it may be in your dependencies. Telltale files like `bootstrap-sphinx.css` and `bootstrap-sphinx.js` are not present and it doesn't look anything like what the theme would do.

To your actual issue, it looks like is most likely a factor of your webserver as it's returning a `301 Moved Permanently` then pointing to the `/` version of the URL in its configuration and your best bet is starting there first.

**Comment by vlcinsky** [comment]
@ryan-roemer thanks for quick reaction.

The url above is not where the docs is present, but which shall be rendered on a documentation.

Actual pages are are at https://lod.tamtamresearch.com/docs/ontology/dtx_srti.html

Anyway, as one can see, even the alabaster theme has the same issue so I think the problem may originate in the rst parser.
