### ISSUE TITLE
Search locally doesn't work

### ISSUE THREAD

**Issue by fjfeijoo** [ryan-roemer/sphinx-bootstrap-theme#82]
Sphinx 1.2 added a workaround to allow searching locally (from file://). That fix included this change in search.html. The last part should be added to the search.html of this template.

Thanks!

```
{% block extrahead %}
  <script type="text/javascript">
    jQuery(function() { Search.loadIndex("{{ pathto('searchindex.js', 1) }}"); });
  </script>
  {# this is used when loading the search index using $.ajax fails,
     such as on Chrome for documents on localhost #}
  <script type="text/javascript" id="searchindexloader"></script>
  {{ super() }}
{% endblock %}
```

**Comment by AndydeCleyre** [comment]
Does this really/still work? It doesn't seem to, using sphinx `3.1.2` and this project's last PyPI release, `0.7.1`. I was looking for an option to totally disable the search because of this, when I found this old issue.
